'use client';

import React from 'react';
import { Input } from './ui/Input';

export interface TokenInputProps {
  inputTokens: number;
  outputTokens: number;
  onInputChange: (val: number) => void;
  onOutputChange: (val: number) => void;
}

export const TokenInput: React.FC<TokenInputProps> = ({
  inputTokens,
  outputTokens,
  onInputChange,
  onOutputChange,
}) => {
  return (
    <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
      <Input
        label="Input Tokens (Per Request)"
        type="number"
        min="0"
        value={inputTokens === 0 ? '' : inputTokens}
        onChange={(e) => onInputChange(parseInt(e.target.value, 10) || 0)}
        placeholder="e.g. 1000"
        helperText="Prompt / context tokens sent to LLM"
      />
      <Input
        label="Output Tokens (Per Request)"
        type="number"
        min="0"
        value={outputTokens === 0 ? '' : outputTokens}
        onChange={(e) => onOutputChange(parseInt(e.target.value, 10) || 0)}
        placeholder="e.g. 500"
        helperText="Completion tokens generated by LLM"
      />
    </div>
  );
};
